# Netlify configuration for BookVerse
# This project is a static single-page HTML app located at the repository root.
[build]
  # No build command required for static HTML; leave blank or set if you add a build step.
  command = ""
  # Publish from the repository root so ubr.html is served directly
  publish = "."

[dev]
  # Optional: local dev server settings when using `netlify dev`
  command = "npm run start"
  port = 8000
